Preserve server state across reloads.
open-craft/ansible-load-balancer pull request #2
Opened 2016-10-10 15:49 UTC by smarnach

These changes make sure the current state of the stick tables is preserved
across reloads.  It also adds options to make sure users get redispatched to a
different backend in case a backend doesn't responde.

2016-10-17 18:32 UTC, bdero requested changes
Other than `socat` being needed in the requirements, this is good. I deployed this change to our haproxy servers and I was able to test/verify that the state save and state loading from the tmp file is working.

Of course, we also need to update the ansible galaxy requirement for this in `deployment-deploy-services`, but I'd suggest pushing that tiny change to the repo without a review after this is merged. :)

2016-10-17 18:32 UTC, bdero commented on templates/haproxy-reload
> +    echo "show servers state" | socat /run/haproxy/admin.sock - > {{ LOAD_BALANCER_STATE_FILE }}
`socat` needs to be added to [`LOAD_BALANCER_APT_PACKAGES`](https://github.com/open-craft/ansible-load-balancer/blob/23df7bc11bbcb27626ee1e98b048e15a65d0227b/defaults/main.yml#L3-L7).

2016-10-18 16:13 UTC, smarnach commented on templates/haproxy-reload
> +    echo "show servers state" | socat /run/haproxy/admin.sock - > {{ LOAD_BALANCER_STATE_FILE }}
I was sure I had done this, but oviously I'm wrong. :)  Added now.

2016-10-18 16:15 UTC, smarnach commented
@bdero Thanks for catching this!  I've pushed a new version, so please take another look.

I'd expect that we might need a few more minor changes while implementing support for the load balancer in the instance manager, so I will wait with updating the hash until all is done.

2016-10-18 17:00 UTC, bdero approved these changes

2016-10-18 17:01 UTC, merged

2016-10-18 17:02 UTC, bdero commented
:+1:

- [x] I tested this: I deployed this change to the load balancers (they're not being used in production yet) and tested to make sure the state was saving/loading.
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~
- [x] ~~Includes documentation~~ This is the reasonable and expected behavior, so I don't think this needs docs. :)