[BB-840] Include the optional unbound role
open-craft/ansible-load-balancer pull request #31
Opened 2019-03-07 18:45 UTC by lgp171188

This will be used by haproxy-stage.

2019-03-11 14:26 UTC, UmanShahzad commented
@lgp171188 This doesn't seem ready for review as the tests are failing for related reasons: https://circleci.com/gh/open-craft/ansible-load-balancer/208?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

2019-03-11 14:36 UTC, UmanShahzad requested changes

2019-03-11 14:36 UTC, UmanShahzad commented on defaults/main.yml
> +caching_resolver_enabled: false
Nit: 1 newline above this

2019-03-11 14:36 UTC, UmanShahzad commented on meta/main.yml
> +    when: caching_resolver_enabled
Nit: put `tags` last since it's metadata

2019-03-11 14:38 UTC, UmanShahzad commented
Another thing: I think the configuration of unbound should probably go into ansible-secrets hosts, and the role should be included within a playbook rather than as a meta? It isn't strictly needed to run a load balancer, so it isn't a 'dependency'.

2019-03-12 06:46 UTC, lgp171188 commented
> This doesn't seem ready for review as the tests are failing for related reasons: https://circleci.com/gh/open-craft/ansible-load-balancer/208?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

@UmanShahzad, I didn't know that this repository has CI checks :open_mouth: I checked the error and it looks like it is related to the CI checks not using the related `ansible-playbooks` PR branch. I can look into it, however that may not be required due to the below comment.

> Another thing: I think the configuration of unbound should probably go into ansible-secrets hosts, and the role should be included within a playbook rather than as a meta? It isn't strictly needed to run a load balancer, so it isn't a 'dependency'.

It makes sense to move this to the `ansible-playbooks` repository :+1: So, if you don't have any objections, I will close this PR and move the changes to the load balancer playbook in the other PR.

2019-03-21 05:04 UTC, lgp171188 commented
Closing this in favor of https://github.com/open-craft/ansible-playbooks/pull/105 which has the changes to conditionally install unbound.

2019-03-21 05:04 UTC, closed without merging